[project]
name = "colmap-experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "enlighten>=1.14.1",
    "matplotlib>=3.10.7",
    "nbformat>=5.10.4",
    "notebook>=7.4.7",
    "opencv-python>=4.12.0.88",
    "pandas>=2.3.3",
    "plotly>=6.3.1",
    "pycolmap>=3.12.6",
    "rerun-sdk>=0.26.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.0.0",
]
