model:
  name: SiameseGCN
  embedding_size: 64
  rotation_representation: matrix

dataset:
  name: samples_v3_rot_and_trans
  include_image_features: true

training:
  num_epochs: 500
  batch_size: 32
  lr: 0.001
  lambda_translation: 0.1
  lambda_frobenius: 0.01
  rotation_loss: l1
  use_frobenius_regularization: true
  scheduler:
    enabled: true
    step_size: 100
    gamma: 0.8
