model:
#  name: SiameseGCN_v6 # TODO update the script to support this usage...
  embedding_size: 16

dataset:
  name: samples_v1_trans_only
  include_image_features: false

training:
  num_epochs: 1000
  batch_size: 64
  lr: 0.001
  lambda_translation: 1.0
  lambda_frobenius: 0.01
  scheduler:
    enabled: true
    step_size: 200
    gamma: 0.8
